language: python

cache: pip

install:
  - pip install --upgrade pipenv
  - pipenv install --dev

script:
  - pipenv check --style .
  - pipenv run python setup.py sdist

deploy:
  provider: pypi
  user: gmarull
  password:
    secure: LLq+d5rGLHj9OGbaLU9SS6R3hTZwMuje+LzNoiIVyC58RVDyLOwR2pDyYzXtg8rJOJ7uf/ASPy3QStlqgfldEtmqyJKrdWqf7yIV7PVtbRsFo3yBOq74PxgSEXl9F20vYu1Z2NI6qeE4Oh6qubfs3e82Qu5Cnkk//jpNNlHdMauxcqA65sbMp8KsdW0Agm0nE7Y5B8WbEfuBLnWa6kTG3Z8o2WrVTKRrOscZ3JBPtxbpF49F+Qfipq3090LAzVbPVNcdZlLHacZ+wQNkRPftf9DHpeI3f+ZBEgu0xZNZm/lrWt3ZsB9UAuTihX0ZKNZfqv+Qglr3js3Lu6mnW70gX5wpW+kLh7/8wJ1TRzyZN3MEI2yrqr2VEMEiVIUqymKryn6N1S+t8Xh8bSDQZGSJRujns4TNps/j+H7lOiCXnjE6Yufp30wx59UATVFFM+e6oU+f7umpHSqz2Bzp1BgsuIyQ4cMi0PDZP9ljkT1ilfPq8DuBTGm9GvPR1c+CLzktArQt5ouZpOlbkKmKN7IDIoaJM8p3Hwf5+zgM/nQ/N1KdM9K5Oi8g/7yVkgzvEgSG+wjvk0B0c+d43ypJ11imvK6RRLCub6Csqy+frHqmCEovzAALJly+Z3uWYMdKIMYaqb0MQhYPawmeIWsW6Fj5xJdfKXx9CDKpoGLX/1xWciE=
  on:
    branch: master
    tags: true
